app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
*/

Route::get('/',
    ['as' => 'home', 'uses' => 'MainController@getHome']
);

Route::get('/contact/{status?}',
    ['as' => 'contact', 'uses' => 'MainController@getContact']
);
Route::post('/contact',
    ['as' => 'enquiry.send', 'uses' => 'EnquiryController@sendEnquiry']
);

Route::get('/our-vw-campervans-for-hire/{slug}',
    ['as' => 'van.show', 'uses' => 'MainController@getVan']
);
Route::get('/our-vw-campervans-for-hire',
    ['as' => 'van.index', 'uses' => 'MainController@getVans']
);

Route::get('/gallery',
    ['as' => 'gallery', 'uses' => 'MainController@getGallery']
);

Route::get('/prices-and-availability/vans',
    ['as' => 'availability.vans',  'uses' => 'AvailabilityController@getVans']
);
Route::get('/prices-and-availability/calendar',
    ['as' => 'availability.calendar',  'uses' => 'AvailabilityController@getCalendar']
);

Route::get('/booking/{slug}', ['as' => 'booking',  'uses' => 'BookingController@getForm']);
Route::post('/booking', ['as' => 'booking.send',  'uses' => 'BookingController@postForm']);
Route::get('/booking-confirmation', ['as' => 'booking.confirmation',  'uses' => 'BookingController@getConfirmation']);
Route::any('/booking-callback', ['as' => 'booking.callback',  'uses' => 'BookingController@postCallback']);

Route::get('travel-guides', array('as' => 'guide.index', 'uses' => 'GuideController@frontendList'));
Route::get('travel-guides/{slug}', array('as' => 'guide.show', 'uses' => 'GuideController@frontendDetail'));

Route::get('blog', array('as' => 'blog.index', 'uses' => 'BlogArticleController@frontendList'));
Route::get('blog/category/{slug}', array('as' => 'blog.category.show', 'uses' => 'BlogCategoryController@frontendDetail'));
Route::get('blog/{slug}', array('as' => 'blog.show', 'uses' => 'BlogArticleController@frontendDetail'));

/*
|--------------------------------------------------------------------------
| User Account Routes
|--------------------------------------------------------------------------
*/
Route::get('account', ['as' => 'account', 'uses' => 'CustomerController@getAccount']);
Route::get('account/edit', ['as' => 'account.edit', 'uses' => 'CustomerController@getCustomer']);
Route::post('account/update', ['as' => 'account.update', 'uses' => 'CustomerController@postCustomer']);
Route::get('account/booking/{ref}', ['as' => 'account.booking', 'uses' => 'CustomerController@getBooking']);
Route::get('account/booking/{ref}/edit', ['as' => 'account.booking.edit', 'uses' => 'CustomerController@getBookingEdit']);
Route::post('account/booking/{ref}/update', ['as' => 'account.booking.update', 'uses' => 'CustomerController@postBookingUpdate']);
Route::post('account/booking/{ref}/payment', ['as' => 'account.booking.payment', 'uses' => 'CustomerController@postBookingPayment']);
Route::get('account/booking/payment/confirm/{ref}', ['as' => 'account.booking.payment.confirm', 'uses' => 'CustomerController@getConfirmPayment']);
Route::get('login', ['as' => 'login', 'uses' => 'CustomerController@getLogin']);
Route::post('login', 'CustomerController@postLogin');
Route::post('password/email', ['as'=>'password.email', 'uses'=>'CustomerController@postEmailPassword']);
Route::get('password/reset/{ref?}',  ['as'=>'password.reset', 'uses'=>'CustomerController@getResetPassword']);
Route::post('password/reset', ['as'=>'password.reset', 'uses'=>'CustomerController@postResetPassword']);
Route::get('logout', ['as' => 'logout', 'uses' => 'CustomerController@getLogout']);


/*
|--------------------------------------------------------------------------
| Preview Routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'preview', 'middleware' => 'admin'], function()
{
    Route::get('travel-guides/{slug}', array('as' => 'preview.guide.show', 'uses' => 'GuideController@frontendPreview'));
    Route::get('blog/{slug}', array('as' => 'preview.blog.show', 'uses' => 'BlogArticleController@frontendPreview'));
    Route::get('{slug}', array('as' => 'preview.page', 'uses' => 'PageController@showPreview'));
});

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/

Route::get('admin/login', ['as' => 'admin.login', 'uses' => 'Auth\AdminAuthController@getLogin']);
Route::post('admin/login', 'Auth\AdminAuthController@postLogin');
Route::get('admin/logout', ['as' => 'admin.logout', 'uses' => 'Auth\AdminAuthController@getLogout']);

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function()
{
    Route::get('/', ['as' => 'admin.dashboard', 'uses' => 'AdminController@dashboard']);
    Route::resource('page', 'PageController');
    Route::resource('banner', 'BannerController');
    Route::resource('setting', 'SettingController');
    Route::resource('enquiry', 'EnquiryController');
    Route::resource('guide', 'GuideController');
    Route::resource('image', 'ImageController');
    Route::resource('blog_article', 'BlogArticleController');
    Route::resource('blog_category', 'BlogCategoryController');
});
Route::post('/admin/order/{resource}', array('as' => 'admin.order', 'uses' => 'AdminController@sortOrder'));

/*
|--------------------------------------------------------------------------
| Sitemap Route
|--------------------------------------------------------------------------
*/
Route::get('sitemap.xml', ['as' => 'sitemap', 'uses' => 'SitemapController@getSitemap']);

/*
|--------------------------------------------------------------------------
| Catch All Page Route
|--------------------------------------------------------------------------
*/
Route::get('/{slug}', array('as' => 'page', 'uses' => 'PageController@showFrontend'));

resources/views/admin/page/create.blade.php
@extends('admin._layout')

@section('content')

<h1 class="page-header">Create Page</h1>

@include('layout.partials.errors')

{!! Form::model($page, array('route' => 'admin.page.store', 'method' => 'POST')) !!}

    <div class="form-group">
        {!! Form::label('heading', 'Heading') !!}
        {!! Form::text('heading', null, array('class' => 'form-control', 'required')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('subheading', 'Sub Heading') !!}
        {!! Form::text('subheading', null, array('class' => 'form-control', 'required')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('slug', 'Slug (URL Name)') !!}
        {!! Form::text('slug', null, array('class' => 'form-control', 'required')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('content', 'Content') !!}
        {!! Form::textarea('content', null, array('class' => 'ckeditor form-control')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('seo_title', 'SEO Title') !!}
        {!! Form::text('seo_title', null, array('class' => 'form-control')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('seo_description', 'SEO Description') !!}
        {!! Form::text('seo_description', null, array('class' => 'form-control')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('published', 'Puiblished?') !!}
        {!! Form::checkbox('published', '1', true, array('class' => 'checkbox')) !!}
    </div>

    {!! Form::submit('Save', array('class' => 'btn btn-success')) !!}
    <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>

{!! Form::close() !!}

<script type="text/javascript">
$(document).ready(function() {
    $('#slug').slugify('#heading');
});
</script>

@stop

resources/views/admin/page/edit.blade.php
@extends('admin._layout')

@section('content')

<h1 class="page-header">Edit Page <small>{!! $page->heading !!}</small></h1>

@include('layout.partials.errors')

{!! Form::model($page, array('route' => array('admin.page.update', $page->id), 'method' => 'PUT')) !!}

    <div class="form-group">
        {!! Form::label('heading', 'Heading') !!}
        {!! Form::text('heading', null, array('class' => 'form-control', 'required')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('subheading', 'Sub Heading') !!}
        {!! Form::text('subheading', null, array('class' => 'form-control', 'required')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('slug', 'Slug (URL Name)') !!}
        {!! Form::text('slug', null, array('class' => 'form-control', 'required')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('content', 'Content') !!}
        {!! Form::textarea('content', null, array('class' => 'ckeditor form-control')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('seo_title', 'SEO Title') !!}
        {!! Form::text('seo_title', null, array('class' => 'form-control')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('seo_description', 'SEO Description') !!}
        {!! Form::text('seo_description', null, array('class' => 'form-control')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('published', 'Puiblished?') !!}
        {!! Form::checkbox('published', '1', $page->published, array('class' => 'checkbox')) !!}
    </div>

    {!! Form::submit('Save', array('class' => 'btn btn-success')) !!}
    <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>

{!! Form::close() !!}

@stop

resources/views/admin/page/index.blade.php
@extends('admin._layout')

@section('content')

<h1 class="page-header">Pages</h1>

@include('flash::message')

<p><a class="btn btn-success" href="{{ URL::route('admin.page.create') }}"><span class="glyphicon glyphicon-plus"></span> Create Page</a></p>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Published?</th>
            <th>Heading</th>
            <th>Slug</th>
            <th width="30%" class="text-right">Actions</th>
        </tr>
    </thead>
    <tbody>
    @foreach($pages as $page)
        <tr id="{{ $page->id }}">
            <td>{{ $page->published ? 'Yes' : 'No' }}</td>
            <td>
                {{ $page->heading }}<br>
                <small>{{ $page->subheading }}</small>
            </td>
            <td>/{{ $page->slug }}</td>
            <td class="text-right">
                <a class="btn btn-small btn-default" href="{{ URL::route('preview.page', array( $page->slug )) }}" target="_blank"><span class="glyphicon glyphicon-new-window"></span> Preview</a>
                <a class="btn btn-small btn-info" href="{{ URL::route('admin.page.edit', array( $page->id )) }}"><span class="glyphicon glyphicon-pencil"></span> Edit Page</a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

{!! $pages->render() !!}

@stop